const API="/api/v1";
const adminState={user:null,schemes:[],reviewAction:null,toastTimer:null};
const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
function cookie(name){const p=`${name}=`;const x=document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith(p));return x?decodeURIComponent(x.slice(p.length)):"";}
async function api(path,options={}){const method=(options.method||"GET").toUpperCase();const headers={"Content-Type":"application/json",...(options.headers||{})};if(!["GET","HEAD","OPTIONS"].includes(method)&&cookie("scheme_mitra_csrf"))headers["X-CSRF-Token"]=cookie("scheme_mitra_csrf");const response=await fetch(API+path,{method,credentials:"same-origin",headers,body:options.body?JSON.stringify(options.body):undefined});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error?.message||data?.detail||`Request failed (${response.status})`);return data;}
function toast(message){const node=document.getElementById("admin-toast");node.textContent=message;node.classList.add("show");clearTimeout(adminState.toastTimer);adminState.toastTimer=setTimeout(()=>node.classList.remove("show"),2800);}
function showAccess(message=""){document.getElementById("admin-access").classList.remove("hidden");document.getElementById("admin-app").classList.add("hidden");document.getElementById("admin-access-error").textContent=message;}
function showApp(user){adminState.user=user;document.getElementById("admin-access").classList.add("hidden");document.getElementById("admin-app").classList.remove("hidden");document.getElementById("admin-session").textContent=`${user.full_name} · ${user.role}`;}
function statusClass(value){return String(value||"").toLowerCase().replace(/[^a-z]+/g,"-");}
function empty(message){return `<div class="admin-empty">${esc(message)}</div>`;}
async function bootstrap(){try{const result=await api("/auth/me");if(!result.authenticated)return showAccess("Sign in first.");if(!["ADMIN","DATA_VERIFIER","SUPER_ADMIN"].includes(result.user.role))return showAccess("Your account does not have data-verifier or administrator access.");showApp(result.user);await loadAll();}catch(error){showAccess(error.message);}}
async function loadAll(){try{const [overview,schemes,pilots,analytics]=await Promise.all([api("/admin/overview"),api("/admin/schemes"),api("/admin/pilots"),api("/admin/analytics")]);adminState.schemes=schemes.schemes;renderOverview(overview,pilots.pilots);renderSchemes();renderAnalytics(analytics);await loadAudit();}catch(error){toast(error.message);}}
function renderOverview(data,pilots){const canPublish=["ADMIN","SUPER_ADMIN"].includes(adminState.user?.role);const items=[["Farmers",data.users,"Accounts created"],["Published schemes",data.published_schemes,"Visible to farmers"],["Needs human review",data.needs_review,"Source/data review queue"],["Recommendations",data.recommendations,"Usage events, not impact"]];document.getElementById("admin-metrics").innerHTML=items.map(([label,value,note])=>`<div class="admin-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`).join("");const needs=adminState.schemes.filter(s=>s.verification_status!=="VERIFIED"||s.status!=="PUBLISHED").slice(0,5);document.getElementById("review-queue").innerHTML=needs.length?needs.map(s=>`<div class="review-row"><div><b>${esc(s.name)}</b><small>${esc(s.source_name)} · ${esc(s.status)}</small></div><button data-admin-edit="${esc(s.slug)}">Review</button></div>`).join(""):empty("No records waiting in this queue.");document.getElementById("pilot-list").innerHTML=pilots.length?pilots.map(p=>`<div class="pilot-row"><div><b>${esc(p.name)}</b><small>${esc(p.location)} · target ${esc(p.target_users)} · ${esc(p.partner_claim)}</small></div><span class="admin-status">${esc(p.status)}</span></div>`).join(""):empty("No pilot has been proposed yet.");document.getElementById("pilot-form").classList.toggle("hidden",!canPublish);}
function renderSchemes(){const q=document.getElementById("scheme-admin-search").value.trim().toLowerCase();const canPublish=["ADMIN","SUPER_ADMIN"].includes(adminState.user?.role);const list=adminState.schemes.filter(s=>!q||`${s.name} ${s.department} ${s.slug}`.toLowerCase().includes(q));document.getElementById("scheme-count-pill").textContent=String(adminState.schemes.length);document.getElementById("scheme-table-body").innerHTML=list.length?list.map(s=>{const actions=[`<button data-admin-edit="${esc(s.slug)}">Edit</button>`];if(s.verification_status!=="VERIFIED")actions.push(`<button data-admin-action="verify" data-slug="${esc(s.slug)}">Verify</button>`);else if(canPublish&&s.status!=="PUBLISHED"){if(s.verified_by===adminState.user?.id)actions.push(`<small class="awaiting-publisher">Needs different publisher</small>`);else actions.push(`<button data-admin-action="publish" data-slug="${esc(s.slug)}">Publish</button>`);}if(canPublish&&s.status!=="ARCHIVED")actions.push(`<button data-admin-action="archive" data-slug="${esc(s.slug)}">Archive</button>`);return `<tr><td><strong>${esc(s.name)}</strong><small>${esc(s.department)} · ${esc(s.slug)}</small></td><td><a href="${esc(s.source_url)}" target="_blank" rel="noreferrer">${esc(s.source_name)} ↗</a><small>Source checked: ${esc(s.source_checked_at||"not recorded")}</small><small>Verified: ${s.verified_by?esc(s.verified_by):"not signed off"} · ${s.last_verified_at?esc(new Date(s.last_verified_at).toLocaleDateString()):"—"}</small></td><td><span class="admin-status ${statusClass(s.status)}">${esc(s.status)}</span><small>${esc(s.verification_status)}</small></td><td><b>v${esc(s.version)}</b></td><td><div class="admin-row-actions">${actions.join("")}</div></td></tr>`;}).join(""):`<tr><td colspan="5">${empty("No scheme records match the search.")}</td></tr>`;}
function renderAnalytics(data){const values=[["Recommendations generated",data.recommendations_generated],["Official portal clicks",data.official_portal_clicks],["Scheme views",data.scheme_views],["Feedback entries",data.feedback_count]];document.getElementById("admin-analytics").innerHTML=values.map(([label,value])=>`<div class="analytics-line"><span>${esc(label)}</span><b>${esc(value)}</b></div>`).join("");}
async function loadAudit(){try{const data=await api("/admin/audit-logs?limit=50");const rows=data.audit_logs;document.getElementById("audit-log-list").innerHTML=rows.length?rows.map(x=>`<div class="audit-row"><div><b>${esc(x.action)} · ${esc(x.entity_type)} ${esc(x.entity_id)}</b><small>${esc(x.reason)} · actor ${esc(x.actor_user_id||"system")}</small></div><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join(""):empty("No audit actions have been recorded.");}catch(error){document.getElementById("audit-log-list").innerHTML=empty(error.message);}}
function switchTab(tab){document.querySelectorAll("[data-admin-tab]").forEach(x=>x.classList.toggle("active",x.dataset.adminTab===tab));document.querySelectorAll("[data-admin-view]").forEach(x=>x.classList.toggle("active",x.dataset.adminView===tab));}
function openEditor(scheme=null){const form=document.getElementById("scheme-form");form.reset();adminState.editingSlug=scheme?.slug||null;document.getElementById("scheme-editor-title").textContent=scheme?"Edit scheme record":"Add scheme record";document.getElementById("change-reason-label").classList.toggle("hidden",!scheme);form.elements.namedItem("change_reason").required=!!scheme;if(scheme){const data=scheme;const fields={slug:data.slug,name:data.name,department:data.department,level:data.level,category:data.category,need:data.need,source_name:data.source_name,source_url:data.source_url,application_url:data.application_url,summary:data.summary,benefit_summary:data.benefit_summary,name_mr:data.name_mr,icon:data.icon,source_checked_at:data.source_checked_at,crop_tags:(data.crop_tags||[]).join(", "),source_facts:(data.source_facts||[]).join("\n"),checks:JSON.stringify(data.checks||[],null,2),document_items:JSON.stringify(data.document_items||[],null,2)};for(const [key,value] of Object.entries(fields)){const input=form.elements.namedItem(key);if(input)input.value=value??"";}form.elements.namedItem("slug").readOnly=true;}else{form.elements.namedItem("slug").readOnly=false;form.elements.namedItem("source_name").value="MahaDBT Farmer Portal";form.elements.namedItem("level").value="State";form.elements.namedItem("category").value="General";form.elements.namedItem("checks").value="[]";form.elements.namedItem("document_items").value="[]";}document.getElementById("scheme-editor").classList.remove("hidden");document.body.style.overflow="hidden";}
function closeModal(id){document.getElementById(id).classList.add("hidden");if(!document.querySelector(".modal-scrim:not(.hidden)"))document.body.style.overflow="";}
function parseLines(value){return String(value||"").split("\n").map(x=>x.trim()).filter(Boolean);}
async function saveScheme(event){event.preventDefault();const form=event.currentTarget;const fd=new FormData(form);let checks,documents;try{checks=JSON.parse(fd.get("checks")||"[]");documents=JSON.parse(fd.get("document_items")||"[]");if(!Array.isArray(checks)||!Array.isArray(documents))throw new Error("The JSON fields must be arrays.");}catch(error){return toast(`Check the JSON fields: ${error.message}`);}const payload={slug:fd.get("slug"),name:fd.get("name"),department:fd.get("department"),level:fd.get("level")||"State",category:fd.get("category")||"General",need:fd.get("need")||"",source_name:fd.get("source_name"),source_url:fd.get("source_url"),application_url:fd.get("application_url")||"",summary:fd.get("summary"),benefit_summary:fd.get("benefit_summary")||"",crop_tags:String(fd.get("crop_tags")||"").split(",").map(x=>x.trim()).filter(Boolean),source_facts:parseLines(fd.get("source_facts")),document_items:documents,checks,name_mr:fd.get("name_mr")||"",icon:fd.get("icon")||"leaf",source_checked_at:fd.get("source_checked_at")||null};try{if(adminState.editingSlug){const reason=String(fd.get("change_reason")||"").trim();if(reason.length<4)return toast("An audit reason is required.");await api(`/admin/schemes/${encodeURIComponent(adminState.editingSlug)}`,{method:"PUT",body:{payload,note:{reason}}});}else{await api("/admin/schemes",{method:"POST",body:payload});}closeModal("scheme-editor");toast("Saved to review queue. It is not published.");await loadAll();}catch(error){toast(error.message);}}
function askAction(action,slug){adminState.reviewAction={action,slug};const scheme=adminState.schemes.find(s=>s.slug===slug);const verb={verify:"Record human verification for",publish:"Publish",archive:"Archive"}[action];document.getElementById("review-title").textContent=`${verb} scheme`;document.getElementById("review-detail").textContent=`${scheme?.name||slug} · version ${scheme?.version||"?"}. This action will be written to the audit log.`;document.getElementById("review-modal").classList.remove("hidden");document.body.style.overflow="hidden";}
async function performAction(event){event.preventDefault();const action=adminState.reviewAction;if(!action)return;const reason=new FormData(event.currentTarget).get("reason");try{await api(`/admin/schemes/${encodeURIComponent(action.slug)}/${action.action}`,{method:"POST",body:{reason}});event.currentTarget.reset();closeModal("review-modal");toast(action.action==="verify"?"Human verification recorded. Publishing remains separate.":`Scheme ${action.action} action complete.`);await loadAll();}catch(error){toast(error.message);}}
async function savePilot(event){event.preventDefault();const fd=new FormData(event.currentTarget);try{await api("/admin/pilots",{method:"POST",body:{name:fd.get("name"),location:fd.get("location"),target_users:Number(fd.get("target_users")||0)}});event.currentTarget.reset();toast("Pilot saved as proposed only.");await loadAll();}catch(error){toast(error.message);}}

for(const button of document.querySelectorAll("[data-admin-tab]"))button.addEventListener("click",()=>switchTab(button.dataset.adminTab));
document.querySelectorAll("[data-admin-goto]").forEach(button=>button.addEventListener("click",()=>switchTab(button.dataset.adminGoto)));
document.getElementById("scheme-admin-search").addEventListener("input",renderSchemes);
document.getElementById("new-scheme").addEventListener("click",()=>openEditor());
document.getElementById("scheme-form").addEventListener("submit",saveScheme);
document.getElementById("review-form").addEventListener("submit",performAction);
document.getElementById("pilot-form").addEventListener("submit",savePilot);
document.getElementById("refresh-audit").addEventListener("click",loadAudit);
document.getElementById("admin-logout").addEventListener("click",async()=>{try{await api("/auth/logout",{method:"POST",body:{}});showAccess("You have signed out.");}catch(error){toast(error.message);}});
document.querySelectorAll("[data-admin-close]").forEach(button=>button.addEventListener("click",()=>closeModal(button.dataset.adminClose)));
document.querySelectorAll(".modal-scrim").forEach(modal=>modal.addEventListener("click",event=>{if(event.target===modal)closeModal(modal.id);}));
document.addEventListener("keydown",event=>{if(event.key==="Escape")document.querySelectorAll(".modal-scrim:not(.hidden)").forEach(modal=>closeModal(modal.id));});
document.addEventListener("click",event=>{const edit=event.target.closest("[data-admin-edit]");if(edit){const scheme=adminState.schemes.find(s=>s.slug===edit.dataset.adminEdit);if(scheme)openEditor(scheme);return;}const action=event.target.closest("[data-admin-action]");if(action)askAction(action.dataset.adminAction,action.dataset.slug);});
document.getElementById("admin-login-form").addEventListener("submit",async event=>{event.preventDefault();const values=new FormData(event.currentTarget);try{const result=await api("/auth/login",{method:"POST",body:{email:values.get("email"),password:values.get("password")}});if(!["ADMIN","DATA_VERIFIER","SUPER_ADMIN"].includes(result.user.role)){showAccess("This account does not have data-verifier or administrator access.");return;}showApp(result.user);await loadAll();}catch(error){showAccess(error.message);}});
bootstrap();
