"""initial production schema

Revision ID: cafed83499ac
Revises: 
Create Date: 2026-10-07 06:21:07.095301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafed83499ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_event_name_created', ['event_name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)

    op.create_table('farmer_crops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('crop_category', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=32), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_acres IS NULL OR area_acres >= 0', name='ck_farmer_crop_area_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_crops_user_id'), ['user_id'], unique=False)

    op.create_table('farmer_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_farmer_document_item')
    )
    with op.batch_alter_table('farmer_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_documents_user_id'), ['user_id'], unique=False)

    op.create_table('farmer_land',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('ownership_type', sa.String(length=24), nullable=False),
    sa.Column('irrigation_available', sa.String(length=16), nullable=False),
    sa.Column('irrigation_type', sa.String(length=64), nullable=False),
    sa.Column('water_source', sa.String(length=64), nullable=False),
    sa.Column('survey_reference', sa.String(length=80), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_acres >= 0', name='ck_farmer_land_area_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_land', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_land_user_id'), ['user_id'], unique=False)

    op.create_table('farmer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('farmer_category', sa.String(length=32), nullable=False),
    sa.Column('social_category', sa.String(length=32), nullable=False),
    sa.Column('support_needs', sa.JSON(), nullable=False),
    sa.Column('aadhaar_present', sa.Boolean(), nullable=True),
    sa.Column('irrigation', sa.String(length=16), nullable=False),
    sa.Column('electric_water_pump', sa.String(length=16), nullable=False),
    sa.Column('permanent_electric_connection', sa.String(length=16), nullable=False),
    sa.Column('prior_micro_benefit_year', sa.String(length=32), nullable=False),
    sa.Column('selected_component', sa.String(length=120), nullable=False),
    sa.Column('selected_machinery', sa.String(length=120), nullable=False),
    sa.Column('previous_same_machinery_year', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.String(length=800), nullable=False),
    sa.Column('source_url', sa.String(length=1200), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('pilot_surveys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('time_minutes', sa.Float(), nullable=True),
    sa.Column('knows_relevant_schemes', sa.Boolean(), nullable=True),
    sa.Column('understands_documents', sa.Boolean(), nullable=True),
    sa.Column('knows_next_step', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pilot_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pilot_surveys_user_id'), ['user_id'], unique=False)

    op.create_table('pilots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('target_users', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('partner_claim', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('department', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1200), nullable=False),
    sa.Column('application_url', sa.String(length=1200), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_schemes_status_category', ['status', 'category'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('status_source', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_applications_user_status', ['user_id', 'status'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('scheme_id', sa.String(length=36), nullable=True),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('profile_match', sa.Integer(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_snapshots_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_snapshots_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_recommendations_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('saved_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scheme_id', name='uq_saved_scheme_user')
    )
    with op.batch_alter_table('saved_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_schemes_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_schemes_user_id'), ['user_id'], unique=False)

    op.create_table('scheme_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=1200), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'version', name='uq_scheme_version')
    )
    with op.batch_alter_table('scheme_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_versions_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('application_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('status_source', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_history_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_history_application_id'))

    op.drop_table('application_status_history')
    with op.batch_alter_table('scheme_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_versions_scheme_id'))

    op.drop_table('scheme_versions')
    with op.batch_alter_table('saved_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_schemes_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_schemes_scheme_id'))

    op.drop_table('saved_schemes')
    with op.batch_alter_table('recommendation_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendations_user_created')
        batch_op.drop_index(batch_op.f('ix_recommendation_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_snapshots_scheme_id'))

    op.drop_table('recommendation_snapshots')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_scheme_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_user_status')
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_scheme_id'))

    op.drop_table('applications')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index('ix_schemes_status_category')
        batch_op.drop_index(batch_op.f('ix_schemes_slug'))

    op.drop_table('schemes')
    op.drop_table('pilots')
    with op.batch_alter_table('pilot_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pilot_surveys_user_id'))

    op.drop_table('pilot_surveys')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_profiles_user_id'))

    op.drop_table('farmer_profiles')
    with op.batch_alter_table('farmer_land', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_land_user_id'))

    op.drop_table('farmer_land')
    with op.batch_alter_table('farmer_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_documents_user_id'))

    op.drop_table('farmer_documents')
    with op.batch_alter_table('farmer_crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_crops_user_id'))

    op.drop_table('farmer_crops')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index('ix_audit_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index('ix_analytics_event_name_created')

    op.drop_table('analytics_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
